[package]
name = "kaleido-core"
version.workspace = true
edition.workspace = true

[dependencies]
tracing.workspace = true
thiserror.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
serde_json.workspace = true
wide.workspace = true

[dev-dependencies]
criterion = "0.8"

[[bench]]
name = "pixel_convert"
harness = false
