[package]
name = "kaleido-desktop"
version.workspace = true
edition.workspace = true

[dependencies]
kaleido-core = { path = "../../crates/kaleido-core" }
kaleido-traits = { path = "../../crates/kaleido-traits" }
kaleido-services = { path = "../../crates/kaleido-services" }
kaleido-tool-brightness = { path = "../../plugins/examples/brightness" }
kaleido-tool-brush = { path = "../../plugins/examples/brush" }
kaleido-tool-invert = { path = "../../plugins/examples/invert" }
anyhow.workspace = true
image.workspace = true
serde_json.workspace = true
smallvec = "1.13"
gpui.workspace = true
gpui_platform.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
