[package]
name = "kaleido-desktop"
version.workspace = true
edition.workspace = true

[dependencies]
kaleido-core = { path = "../../crates/kaleido-core" }
kaleido-traits = { path = "../../crates/kaleido-traits" }
kaleido-services = { path = "../../crates/kaleido-services" }
anyhow.workspace = true
image.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
smallvec = "1.13"
futures = "0.3"
gpui-kit.workspace = true
rust-i18n.workspace = true
once_cell.workspace = true
serde = { workspace = true, features = ["derive"] }
cordis-rs.workspace = true
sys-locale = "0.3"
