[package]
name = "kaleido-tool-brush"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
kaleido-core = { path = "../../../crates/kaleido-core" }
kaleido-traits = { path = "../../../crates/kaleido-traits" }
serde_json.workspace = true
