[package]
name = "kaleido-plugin-host"
version.workspace = true
edition.workspace = true

[dependencies]
kaleido-core = { path = "../kaleido-core" }
kaleido-traits = { path = "../kaleido-traits" }
cordis-rs.workspace = true
thiserror.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
